// <auto-generated />
using System;
using JobApplicationTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JobApplicationTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Applied");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName", "Position");

                    b.ToTable("JobApplications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Google",
                            DateApplied = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 15, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Initial phone screen complete.",
                            Position = "Backend Engineer",
                            Status = "Shortlisted"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Apple",
                            DateApplied = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Waiting for recruiter feedback.",
                            Position = "Full Stack Developer",
                            Status = "InProcess"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Microsoft",
                            DateApplied = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 2, 14, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Offer expires next week.",
                            Position = "Site Reliability Engineer",
                            Status = "Offer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
