// <auto-generated />
using System;
using JobApplicationTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JobApplicationTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName", "Position");

                    b.ToTable("JobApplications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Google",
                            DateApplied = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 15, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Initial phone screen complete.",
                            Position = "Backend Engineer",
                            Status = "Shortlisted"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Apple",
                            DateApplied = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Waiting for recruiter feedback.",
                            Position = "Full Stack Developer",
                            Status = "InProcess"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Microsoft",
                            DateApplied = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 2, 14, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Offer expires next week.",
                            Position = "Site Reliability Engineer",
                            Status = "Offer"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon",
                            DateApplied = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 3, 6, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Preparing technical assessment.",
                            Position = "Cloud Support Engineer",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Meta",
                            DateApplied = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 2, 5, 16, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Panel interview scheduled for next week.",
                            Position = "Machine Learning Engineer",
                            Status = "Interview"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Netflix",
                            DateApplied = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 2, 25, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Position = "Security Engineer",
                            Status = "InProcess"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Salesforce",
                            DateApplied = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 25, 13, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Awaiting hiring manager feedback.",
                            Position = "DevOps Engineer",
                            Status = "Shortlisted"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Atlassian",
                            DateApplied = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2024, 12, 10, 8, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Received polite decline.",
                            Position = "Frontend Developer",
                            Status = "Declined"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Adobe",
                            DateApplied = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 3, 2, 10, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Portfolio submitted.",
                            Position = "Product Designer",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Shopify",
                            DateApplied = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 2, 18, 15, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "On-site scheduled.",
                            Position = "Infrastructure Engineer",
                            Status = "Interview"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Stripe",
                            DateApplied = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 1, 10, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Reviewing offer details.",
                            Position = "Payments Engineer",
                            Status = "Offer"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Tesla",
                            DateApplied = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2025, 3, 13, 7, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Position = "Automation Engineer",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Airbnb",
                            DateApplied = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedOn = new DateTimeOffset(new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "Role closed before interview.",
                            Position = "Platform Engineer",
                            Status = "PositionClosed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
